### PR TITLE
Don't render parens for case objects in union member nodes

### LINKED ISSUE #1599: Unit members of unions have invalid TypedNode rendering
To reproduce, generate and compile the code for:

```smithy
$version: "2"

namespace demo

@trait
union aaa {
    u: Unit
    s: String
}

@aaa(u: {

})
string Hello

```

The error:

```scala
[error] ./demo/Hello.scala:13:5
[error] object UCase in object Aaa does not take parameters
[error]     demo.Aaa.UCase(()).widen,
[error]     ^^^^^^^^^^^^^^
```

The actual signature of `UCase` is `case object UCase`, indeed with no parameters.

This has been discovered in the latest spec for SNS, in one of the smoke test traits.

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #1599

## PR Checklist (not all items are relevant to all PRs)

- [ ] Added unit-tests (for runtime code)
- [x] Added bootstrapped code + smoke tests (when the rendering logic is modified)
- [ ] Added build-plugins integration tests (when reflection loading is required at codegen-time)
- [ ] Added alloy compliance tests (when simpleRestJson protocol behaviour is expanded/updated)
- [ ] Updated dynamic module to match generated-code behaviour
- [ ] Added documentation
- [x] Updated changelog

### CODE REVIEW

File: modules/codegen/src/smithy4s/codegen/internals/IR.scala [hunk 1]
```diff
@@ -426,6 +427,7 @@ private[internals] object TypedNode {
     def map[B](f: A => B): AltValueTN[B] = this match {
       case ProductAltTN(value) => ProductAltTN(f(value))
       case TypeAltTN(value)    => TypeAltTN(f(value))
+      case UnitAltTN           => UnitAltTN
```
Comment (kubukoz) [inline modules/codegen/src/smithy4s/codegen/internals/IR.scala:430]: thought: this is my third implementation of the fix, I think it's the most principled as `AltValueTN` now more accurately mirrors the `UnionMember` ADT used on the schema side of things.

File: modules/codegen/src/smithy4s/codegen/internals/SmithyToIR.scala [hunk 2]
```diff
@@ -1151,21 +1153,17 @@ private[codegen] class SmithyToIR(
...
         .members()
         .asScala
-        .map { member =>
-          val memberTarget =
-            model.expectShape(member.getTarget)
-          if (isPartOfAdt(memberTarget)) {
-            (member.getMemberName(), member.tpe.map(Left(_)))
-          } else {
-            (member.getMemberName(), member.tpe.map(Right(_)))
+        .flatMap { member =>
```
Comment (kubukoz) [inline modules/codegen/src/smithy4s/codegen/internals/SmithyToIR.scala:1156]: note: this change is no longer necessary, it's merely a refactor. I left it in because the original seemed needlessly duplicative.

**Review by Baccata — APPROVED** [review]
