### PR TITLE
fix for hints in union->unit case

### LINKED ISSUE #1804: Hints are not rendered on Union members when they are targeting Unit
In the case of  a standard Union shape such as below, when a member targets the Unit shape, hints are not added to it.
In this particular case , notice the documentation hint is not added to the schema the represents the unit member.

Smithy:

```smithy
$version: "2"

namespace example

union Test {
    @jsonName("text")
    t:Text
    @documentation("no_text")
    noText: Unit
}

structure Text {
    @required
    body: String

}

```

Generated Code :

```scala

sealed trait Test extends scala.Product with scala.Serializable { self =>
  @inline final def widen: Test = this
  def $ordinal: Int

  object project {
    def t: Option[Text] = Test.TCase.alt.project.lift(self).map(_.t)
    def noText: Option[Test.NoTextCase.type] = NoTextCaseAlt.project.lift(self)
  }

  def accept[A](visitor: Test.Visitor[A]): A = this match {
    case value: Test.TCase => visitor.t(value.t)
    case value: Test.NoTextCase.type => visitor.noText(value)
  }
}
object Test extends ShapeTag.Companion[Test] {

  def t(t: Text): Test = TCase(t)
  /** no_text */
  def noText(): Test = Test.NoTextCase

  val id: ShapeId = ShapeId("example", "Test")

  val hints: Hints = Hints.empty

  final case class TCase(t: Text) extends Test { final def $ordinal: Int = 0 }
  /** no_text */
  case object NoTextCase extends Test { final def $ordinal: Int = 1 }
  private val NoTextCaseAlt = Schema.constant(Test.NoTextCase).oneOf[Test]("noText").addHints(hints)

  object TCase {
    val hints: Hints = Hints(
      smithy.api.JsonName("text"),
    ).lazily
    val schema: Schema[Test.TCase] = bijection(Text.schema.addHints(hints), Test.TCase(_), _.t)
    val alt = schema.oneOf[Test]("t")
  }

  trait Visitor[A] {
    def t(value: Text): A
    def noText(value: Test.NoTextCase.type): A
  }

  object Visitor {
    trait Default[A] extends Visitor[A] {
      def default: A
      def t(value: Text): A = default
      def noText(value: Test.NoTextCase.type): A = default
    }
  }

  implicit val schema: Schema[Test] = union(
    Test.TCase.alt,
    NoTextCaseAlt,
  ){
    _.$ordinal
  }.withId(id).addHints(hints)
}
```

### PR DESCRIPTION
**Pull request by yisraelU**
closes #1804 
- adds an additional val in the Union companion object to hold the hints of the specific member and adds them to the `addHints` method call
- the adtmember smithy spec was used to test , as it already contained the use case of a union with a member targeting Unit. 
    -  This created the need to fix the AdtSmokeSpec

### CODE REVIEW

**Review by lewisjkl — APPROVED** [review]

**Comment by lewisjkl** [comment]
I think there are some super edge cases where we could have naming collisions with the `val myAltHints` that we are creating now, but the same is true of the `Alt` suffix we are adding in the same spot, so I think probably not worth worrying about too much right now

**Comment by yisraelU** [comment]
@lewisjkl perhaps the val , should be scoped inside the `case object ` ?

**Comment by lewisjkl** [comment]
> @lewisjkl perhaps the val , should be scoped inside the `case object ` ?

Yeah that's a good idea actually, better safe than sorry even if the edge case is pretty unlikely

File: modules/bootstrapped/src/generated/smithy4s/example/OrderType.scala [hunk 1]
```diff
@@ -65,8 +65,13 @@ object OrderType extends ShapeTag.Companion[OrderType] {
 
     val alt = schema.oneOf[OrderType]("inStore")
   }
-  case object PreviewCase extends OrderType { final def $ordinal: Int = 2 }
-  private val PreviewCaseAlt = Schema.constant(OrderType.PreviewCase).oneOf[OrderType]("preview").addHints(hints)
+  case object PreviewCase extends OrderType {
+    final def $ordinal: Int = 2
+    val PreviewCaseHints: Hints = Hints(
```
Comment (kubukoz) [inline modules/bootstrapped/src/generated/smithy4s/example/OrderType.scala]: **suggestion:** rename to just hints? and let's move the alts inside as well? (with the name `alt` like the non-case-object cases)

Comment (lewisjkl) [reply modules/bootstrapped/src/generated/smithy4s/example/OrderType.scala]: Yeah I agree, we can move the alts in as well since they are private it shouldn't break anything out in the wild

**Review by lewisjkl — APPROVED** [review]

File: modules/codegen/src/smithy4s/codegen/internals/Renderer.scala [hunk 2]
```diff
@@ -1713,8 +1714,8 @@ private[internals] class Renderer(compilationUnit: CompilationUnit) { self =>
     line"val tag: $EnumTag_[$parentType] = $EnumTag_.$tagStr"
   }
 
-  def renderHintsVal(hints: List[Hint]): Lines = {
-    val lhs = line"val hints: $Hints_"
+  def renderHintsVal(hints: List[Hint], prefix: Option[String] = None): Lines = {
```
Comment (kubukoz) [inline modules/codegen/src/smithy4s/codegen/internals/Renderer.scala:1717]: **nitpick:** I don't think `prefix` actually gets passed now

Comment (yisraelU) [reply modules/codegen/src/smithy4s/codegen/internals/Renderer.scala:1717]: yeah , its not needed anymore , figured it still might be useful in the future..
I'll remove in future pr
