### PR TITLE
Fix decoding an optional `Document.DNull` field

### LINKED ISSUE #697: Decoding an optional field fails when receiving a Document.DNull
I noticed that the DocumentDecoderSchemaVisitor will produce a decoder that always fails on DNull,
As null is both a valid json value and smithy value, shouldnt this be handled ?

### PR DESCRIPTION
**Pull request by zetashift**
Fixes: https://github.com/disneystreaming/smithy4s/issues/697

Test was made from kubukoz's reproduction example:
```scala
//> using scala "3.2.1"
//> using lib "com.disneystreaming.smithy4s::smithy4s-core:0.17.2"
import smithy4s.schema.Schema
import smithy4s.Document

@main def demo = println {
  val optionalFieldSchema =
    Schema
      .struct[Option[String]](Schema.string.optional[Option[String]]("test", identity))(identity)

  Document
    .Decoder
    .fromSchema(optionalFieldSchema)
    .decode(Document.obj("test" -> Document.DNull))
}
```

### CODE REVIEW

File: modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala [hunk 1]
```diff
@@ -323,6 +322,7 @@ class DocumentDecoderSchemaVisitor(
           val path = PayloadPath.Segment(jLabel) :: pp
           fields
             .get(jLabel) match {
+            case Some(DNull) => buffer(None)
```
Comment (kubukoz) [inline modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala:325]: **issue:** this is exactly what I was thinking, how dare you steal my ideas :P `/s`

**Review by kubukoz — APPROVED** [review]

**Comment by kubukoz** [comment]
Thanks for the contribution @zetashift!

File: modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala (hunk 1 above)
Comment (zetashift) [reply modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala:325]: Haha, great minds think alike? 👀
