### PR TITLE
Fix refined newtypes

### LINKED ISSUE #1594: AWS: Latest Location service can't be compiled (could not find implicit value for parameter constraint: smithy4s.RefinementProvider)
To reproduce:

1. generate code for this: https://github.com/aws/aws-sdk-js-v3/blob/b06a8b7d9d2a0ca2fc73acdbf37220575b0f1945/codegen/sdk-codegen/aws-models/location.json (making sure to include the fix from #1593)
2. Set `smithy4sAllowedNamespaces` so that the generated code also includes `aws.cloudformation` and `smithy.rules` (which would normally be excluded)
3. Try to compile

Result:

```scala
[error] main/smithy4s/com/amazonaws/location/BatchGetDevicePositionRequest.scala:32:34: could not find implicit value for parameter constraint: smithy4s.RefinementProvider.Simple[smithy.api.Length,com.amazonaws.location.ResourceName]
[error]     ResourceName.schema.validated(smithy.api.Length(min = Some(1L), max = None)).required[BatchGetDevicePositionRequest]("TrackerName", _.trackerName).addHints(smithy.api.Documentation("<p>The tracker resource retrieving the device position.</p>"), smithy.api.HttpLabel()),
[error]                                  ^
[error] main/smithy4s/com/amazonaws/location/BatchGetDevicePositionRequest.scala:34:5: missing argument list for method make in object BatchGetDevicePositionRequest
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `make _` or `make(_,_)` instead of `make`.
[error]   )(make).withId(id).addHints(hints)
[error]     ^
[error] main/smithy4s/com/amazonaws/location/SearchPlaceIndexForSuggestionsRequest.scala:95:37: could not find implicit value for parameter constraint: smithy4s.RefinementProvider.Simple[smithy.api.Length,com.amazonaws.location.SensitiveString]
[error]     SensitiveString.schema.validated(smithy.api.Length(min = Some(1L), max = Some(200L))).required[SearchPlaceIndexForSuggestionsRequest]("Text", _.text).addHints(smithy.api.Documentation("<p>The free-form partial text to use to generate place suggestions. For example,\n                <code>eiffel tow</code>.</p>")),
[error]                                     ^
[error] main/smithy4s/com/amazonaws/location/SearchPlaceIndexForSuggestionsRequest.scala:103:5: missing argument list for method make in object SearchPlaceIndexForSuggestionsRequest
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `make _` or `make(_,_,_,_,_,_,_,_,_)` instead of `make`.
[error]   )(make).withId(id).addHints(hints)
[error]     ^
[error] main/smithy4s/com/amazonaws/location/SearchPlaceIndexForTextRequest.scala:94:37: could not find implicit value for parameter constraint: smithy4s.RefinementProvider.Simple[smithy.api.Length,com.amazonaws.location.SensitiveString]
[error]     SensitiveString.schema.validated(smithy.api.Length(min = Some(1L), max = Some(200L))).required[SearchPlaceIndexForTextRequest]("Text", _.text).addHints(smithy.api.Documentation("<p>The address, name, city, or region to be used in the search in free-form text format.\n            For example, <code>123 Any Street</code>.</p>")),
[error]                                     ^
[error] main/smithy4s/com/amazonaws/location/SearchPlaceIndexForTextRequest.scala:102:5: missing argument list for method make in object SearchPlaceIndexForTextRequest
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `make _` or `make(_,_,_,_,_,_,_,_,_)` instead of `make`.
[error]   )(make).withId(id).addHints(hints)
[error]     ^
[error] 6 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Sep 27, 2024, 1:24:14 AM
```

Looking for a smaller reproduction,  but I think we're dealing with a problem that affects member refinements applied to newtypes (specifically `@length`).

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #1594.

## PR Checklist (not all items are relevant to all PRs)

- [ ] Added unit-tests (for runtime code)
- [ ] Added bootstrapped code + smoke tests (when the rendering logic is modified)
- [ ] Added build-plugins integration tests (when reflection loading is required at codegen-time)
- [ ] Added alloy compliance tests (when simpleRestJson protocol behaviour is expanded/updated)
- [ ] Updated dynamic module to match generated-code behaviour
- [ ] Added documentation
- [x] Updated changelog

### CODE REVIEW

File: modules/core/src/smithy4s/RefinementProvider.scala [hunk 1]
```diff
@@ -202,9 +202,14 @@ private[smithy4s] trait LowPriorityImplicits {
       : RefinementProvider[Pattern, E, E] =
     new RefinementProvider.PatternConstraint[E](e => e.value)
 
-  implicit def isomorphismConstraint[C, A, A0](implicit
+  @deprecated("Use isomorphismConstraint2 instead", "0.18.25")
```
Comment (kubukoz) [inline modules/core/src/smithy4s/RefinementProvider.scala:205]: **thought:** for bincompat, we have to keep the old method.

Comment (kubukoz) [reply modules/core/src/smithy4s/RefinementProvider.scala:205]: I tried to make it `private[smithy4s]` but MiMa complained about the static forwarder disappearing. Figured I'd restore the method to the public scope, it doesn't hurt if it's not implicit anymore.

**Review by Baccata — APPROVED** [review]
